using AIJobExposure.Models;

namespace AIJobExposure.Data;

/// <summary>EU-27 occupations. Employment in thousands. Employment change % is 3-year Eurostat LFS trend (approx 2021–2024).</summary>
public static class EuOccupationData
{
    public static List<Occupation> Get() => new()
    {
        // ── Healthcare & Social Care ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
        new("eu-rn",     "Registered Nurses",              "Healthcare & Social Care","healthcare","#1d4e89", 3800, 4.0,"Low",      "Patient care and clinical assessment require physical presence and human empathy across all EU health systems.",                     "€38,000",38000,"Bachelor's",         +6.2, "Growing",  "Eurostat LFS / ECDC 2024"),
        new("eu-doc",    "Medical Doctors",                "Healthcare & Social Care","healthcare","#1d4e89", 2100, 5.0,"Moderate", "AI diagnostic tools are advancing but physician accountability and patient trust require human doctors.",                           "€75,000",75000,"Doctoral/Prof",      +3.8, "Growing",  "Eurostat LFS / CPME 2024"),
        new("eu-cw",     "Care Workers & Home Carers",     "Healthcare & Social Care","healthcare","#1d4e89", 9500, 2.0,"Minimal",  "Europe's ageing population drives care demand. Physical and emotional caregiving is extremely difficult to automate.",              "€24,000",24000,"No degree/HS",      +10.1, "Growing",  "Eurostat / ECEC 2024"),
        new("eu-ph",     "Pharmacists",                    "Healthcare & Social Care","healthcare","#1d4e89",  750, 6.0,"Moderate", "Automated dispensing is common in hospitals. Community pharmacy counselling retains human involvement.",                            "€45,000",45000,"Master's",           +2.4, "Stable",   "Eurostat LFS / PGEU 2024"),
        new("eu-dent",   "Dentists",                       "Healthcare & Social Care","healthcare","#1d4e89",  500, 3.0,"Low",      "Manual dexterity and patient management are central. AI aids diagnostics but cannot perform treatment.",                            "€65,000",65000,"Doctoral/Prof",      +1.9, "Stable",   "Eurostat LFS / CED 2024"),
        new("eu-sw",     "Social Workers",                 "Healthcare & Social Care","healthcare","#1d4e89", 1200, 4.0,"Low",      "EU social protection systems rely on human caseworkers for safeguarding and family support.",                                       "€34,000",34000,"Bachelor's",         +4.2, "Growing",  "Eurostat LFS 2024"),
        new("eu-rad",    "Medical Radiographers",          "Healthcare & Social Care","healthcare","#1d4e89",  280, 7.0,"High",     "AI radiology tools already match radiologist accuracy in many imaging tasks.",                                                      "€42,000",42000,"Bachelor's",         +3.7, "Stable",   "Eurostat / ESR 2024"),
        new("eu-mid",    "Midwives",                       "Healthcare & Social Care","healthcare","#1d4e89",  350, 3.0,"Low",      "Physical care during pregnancy, birth and postnatal periods requires human presence and judgement.",                                 "€36,000",36000,"Bachelor's",         +2.1, "Stable",   "Eurostat 2024"),

        // ── Education & Training ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
        new("eu-pt",     "Primary School Teachers",        "Education & Training","education","#2d6a4f", 2500, 3.0,"Low",      "Child development and primary education require human-centred pedagogy.",                                                                "€34,000",34000,"Bachelor's",         -0.6, "Stable",   "Eurostat / Eurydice 2024"),
        new("eu-st",     "Secondary School Teachers",      "Education & Training","education","#2d6a4f", 2200, 4.0,"Low",      "Subject expertise and mentorship require human presence. AI automates administrative burden.",                                           "€40,000",40000,"Bachelor's",         +0.9, "Stable",   "Eurostat / Eurydice 2024"),
        new("eu-ul",     "University Lecturers",           "Education & Training","education","#2d6a4f", 1800, 5.0,"Moderate", "EU universities produce significant research. Lecture delivery and standard assessment are AI-automatable.",                             "€52,000",52000,"Doctoral/Prof",      +2.1, "Stable",   "Eurostat / EUA 2024"),
        new("eu-vt",     "Vocational Training Instructors","Education & Training","education","#2d6a4f",  800, 5.0,"Moderate", "Practical skills instruction requires physical demonstration. Course content is heavily AI-automatable.",                                "€32,000",32000,"Post-16/Vocational", -1.8, "Stable",   "Eurostat / CEDEFOP 2024"),
        new("eu-ta",     "Teaching Assistants",            "Education & Training","education","#2d6a4f", 1500, 5.0,"Moderate", "SEND and classroom support are human; administrative tasks are increasingly AI-assisted.",                                               "€24,000",24000,"Post-16/Vocational", -1.4, "Stable",   "Eurostat 2024"),
        new("eu-ey",     "Early Years Workers",            "Education & Training","education","#2d6a4f", 1800, 2.0,"Minimal",  "Physical care and play-based development require constant human presence.",                                                              "€20,000",20000,"No degree/HS",       -2.1, "Growing",  "Eurostat 2024"),

        // ── Technology & IT ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
        new("eu-sd",     "Software Developers",            "Technology & IT","technology","#6b2d8b", 4200, 8.0,"High",     "EU tech sector faces same AI coding disruption as globally. Architectural and oversight roles retain value.",                                "€65,000",65000,"Bachelor's",        +14.8, "Growing",  "Eurostat / DIGITALEUROPE 2024"),
        new("eu-da",     "Data Analysts & Scientists",     "Technology & IT","technology","#6b2d8b", 1200, 9.0,"Very High","Routine analytics are almost entirely automatable. EU GDPR compliance advisory and complex modelling retain value.",                         "€58,000",58000,"Bachelor's",        +19.7, "Growing",  "Eurostat / DIGITALEUROPE 2024"),
        new("eu-itm",    "IT Managers",                    "Technology & IT","technology","#6b2d8b", 1500, 6.0,"Moderate", "Strategic IT leadership and EU regulatory compliance (GDPR, AI Act) require experienced human IT managers.",                                "€72,000",72000,"Bachelor's",         +4.9, "Stable",   "Eurostat 2024"),
        new("eu-cs",     "Cybersecurity Specialists",      "Technology & IT","technology","#6b2d8b",  800, 7.0,"High",     "AI threat detection is standard. NIS2 compliance and adversarial strategy require humans.",                                                  "€70,000",70000,"Bachelor's",        +17.6, "Growing",  "Eurostat / ENISA 2024"),
        new("eu-ux",     "UX & UI Designers",              "Technology & IT","technology","#6b2d8b",  500, 7.0,"High",     "Generative design tools accelerate UI production. Strategic UX research and EU Accessibility Act compliance need humans.",                  "€52,000",52000,"Bachelor's",         +7.3, "Stable",   "Eurostat 2024"),
        new("eu-its",    "IT Support Technicians",         "Technology & IT","technology","#6b2d8b", 1200, 6.0,"Moderate", "AI helpdesk is reducing Tier 1 and 2 support needs. Complex infrastructure support persists.",                                               "€32,000",32000,"Post-16/Vocational", -6.4, "Declining","Eurostat 2024"),
        new("eu-ne",     "Network Engineers",              "Technology & IT","technology","#6b2d8b",  900, 6.0,"Moderate", "Physical infrastructure deployment resists automation. Monitoring is AI-assisted.",                                                          "€50,000",50000,"Post-16/Vocational", -1.8, "Stable",   "Eurostat 2024"),

        // ── Finance & Insurance ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
        new("eu-ac",     "Accountants & Auditors",         "Finance & Insurance","finance","#7b3f00", 2800, 8.0,"High",     "EU audit standards are being transformed by AI. Advisory and regulatory interpretation retain human value.",                                "€50,000",50000,"Bachelor's",         -3.8, "Stable",   "Eurostat / FEE 2024"),
        new("eu-fa",     "Financial Analysts",             "Finance & Insurance","finance","#7b3f00", 1200, 8.0,"High",     "Algorithmic trading and ESG scoring are highly automatable. Complex structured finance is less so.",                                        "€62,000",62000,"Bachelor's",         +1.9, "Stable",   "Eurostat / EFAMA 2024"),
        new("eu-iu",     "Insurance Underwriters",         "Finance & Insurance","finance","#7b3f00",  350, 8.0,"High",     "Telematics and AI pricing algorithms are transforming underwriting. Novel risk assessment retains humans.",                                 "€48,000",48000,"Bachelor's",         -9.3, "Declining","Eurostat / Insurance Europe 2024"),
        new("eu-bc",     "Bank Clerks & Cashiers",         "Finance & Insurance","finance","#7b3f00",  800, 9.0,"Very High","EU bank branch networks are shrinking rapidly. Transactional banking is almost entirely digital.",                                          "€28,000",28000,"No degree/HS",      -19.8, "Declining","Eurostat / EBF 2024"),
        new("eu-fad",    "Financial Advisers",             "Finance & Insurance","finance","#7b3f00", 1100, 6.0,"Moderate", "MiFID II requirements keep human advisers central to complex financial planning.",                                                          "€55,000",55000,"Bachelor's",         +1.7, "Stable",   "Eurostat / EFPA 2024"),
        new("eu-act",    "Actuaries",                      "Finance & Insurance","finance","#7b3f00",  200, 8.0,"High",     "Core actuarial calculations are AI-automatable. Regulatory sign-off and novel risk modelling require qualified actuaries.",                 "€80,000",80000,"Master's",           +2.8, "Stable",   "Eurostat / AAE 2024"),

        // ── Legal & Professional ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
        new("eu-sol",    "Solicitors & Notaries",          "Legal & Professional","legal","#4a1942", 1200, 7.0,"High",     "EU civil law systems create distinct notarial roles. Document AI is transforming the sector.",                                               "€60,000",60000,"Doctoral/Prof",      +2.9, "Stable",   "Eurostat / CCBE 2024"),
        new("eu-para",   "Paralegals & Legal Assistants",  "Legal & Professional","legal","#4a1942",  800, 8.0,"High",     "Contract review and due diligence are highly automatable. EU AI Act compliance creates some new roles.",                                    "€32,000",32000,"Bachelor's",         -7.2, "Declining","Eurostat 2024"),
        new("eu-mc",     "Management Consultants",         "Legal & Professional","legal","#4a1942",  900, 7.0,"High",     "Benchmarking and market research are largely AI-driven. EU regulatory strategy and transformation are resilient.",                          "€78,000",78000,"Master's",           +4.6, "Stable",   "Eurostat / FEACO 2024"),
        new("eu-hrc",    "HR Consultants",                 "Legal & Professional","legal","#4a1942",  500, 6.0,"Moderate", "EU employment law complexity (Works Councils, codetermination) requires human expertise.",                                                   "€48,000",48000,"Bachelor's",         +2.8, "Stable",   "Eurostat 2024"),

        // ── Retail & Customer Service ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
        new("eu-rsa",    "Retail Sales Assistants",        "Retail & Customer Service","retail","#a05c00",18000, 6.0,"Moderate","Physical stocking and premium service persist. Automation of checkout and basic service is progressing.",                                "€23,000",23000,"No degree/HS",       -6.8, "Declining","Eurostat / EuroCommerce 2024"),
        new("eu-cash",   "Cashiers",                       "Retail & Customer Service","retail","#a05c00", 2500, 9.0,"Very High","Self-checkout proliferation across EU retail is displacing cashier roles universally.",                                                 "€22,000",22000,"No degree/HS",      -15.4, "Declining","Eurostat 2024"),
        new("eu-csa",    "Customer Service Agents",        "Retail & Customer Service","retail","#a05c00", 4500, 8.0,"High",    "Multilingual AI chatbots suit EU's diverse languages. Complex cases retain human agents.",                                               "€26,000",26000,"No degree/HS",      -10.2, "Declining","Eurostat / EESC 2024"),
        new("eu-smgr",   "Sales Managers",                 "Retail & Customer Service","retail","#a05c00", 1500, 6.0,"Moderate","Cross-border EU sales and cultural adaptation require human managers. Analytics are AI-driven.",                                         "€55,000",55000,"Bachelor's",         +1.8, "Stable",   "Eurostat 2024"),
        new("eu-buy",    "Buyers & Procurement Officers",  "Retail & Customer Service","retail","#a05c00",  800, 7.0,"High",    "Demand forecasting and supplier comparison are AI-generated. Strategic sourcing relationships are resilient.",                          "€44,000",44000,"Bachelor's",         +2.9, "Stable",   "Eurostat 2024"),

        // ── Transport & Logistics ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
        new("eu-hgv",    "HGV / Truck Drivers",            "Transport & Logistics","transport","#0a4b6e", 3500, 4.0,"Low",      "EU road haulage underpins the single market. Regulatory and cross-border complexity delays autonomous trucks.",                          "€34,000",34000,"Post-16/Vocational", -2.8, "Stable",   "Eurostat / IRU 2024"),
        new("eu-del",    "Delivery Drivers",               "Transport & Logistics","transport","#0a4b6e", 3000, 4.0,"Low",      "E-commerce growth sustains demand. AI optimises routing but last-mile delivery remains human.",                                          "€26,000",26000,"No degree/HS",      +12.6, "Stable",   "Eurostat 2024"),
        new("eu-war",    "Warehouse Operatives",           "Transport & Logistics","transport","#0a4b6e", 5000, 5.0,"Moderate", "EU logistics hubs lead automated warehouse adoption. Transition is underway but not universal.",                                         "€26,000",26000,"No degree/HS",       +2.8, "Declining","Eurostat / ELA 2024"),
        new("eu-lm",     "Logistics & Supply Chain Mgrs",  "Transport & Logistics","transport","#0a4b6e", 1200, 6.0,"Moderate", "EU supply chain complexity and crisis resilience require experienced human strategists.",                                                "€58,000",58000,"Bachelor's",         +5.4, "Stable",   "Eurostat 2024"),
        new("eu-pilot",  "Airline Pilots",                 "Transport & Logistics","transport","#0a4b6e",  180, 3.0,"Low",      "EASA regulations mandate two pilots. Full autonomous commercial flight is many decades away.",                                           "€95,000",95000,"Post-16/Vocational", +9.1, "Growing",  "Eurostat / EASA 2024"),
        new("eu-rail",   "Train Drivers & Rail Workers",   "Transport & Logistics","transport","#0a4b6e",  600, 4.0,"Low",      "Some EU metro systems are automated but mainline rail retains human drivers for decades.",                                               "€40,000",40000,"Post-16/Vocational", -1.2, "Stable",   "Eurostat / CER 2024"),

        // ── Construction & Trades ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
        new("eu-elec",   "Electricians",                   "Construction & Trades","construction","#5c4000", 2200, 2.0,"Minimal",  "EU green energy transition (solar, EV, heat pumps) drives strong demand. Physical installation resists automation.",                  "€38,000",38000,"Post-16/Vocational",+11.8, "Growing",  "Eurostat / ERIG 2024"),
        new("eu-plumb",  "Plumbers & Heating Engineers",   "Construction & Trades","construction","#5c4000", 1500, 2.0,"Minimal",  "Heat pump and hydrogen boiler installation creates sustained demand across EU.",                                                      "€36,000",36000,"Post-16/Vocational", +8.2, "Growing",  "Eurostat 2024"),
        new("eu-brick",  "Bricklayers & Construction Workers","Construction & Trades","construction","#5c4000",3500,2.0,"Minimal","EU housing shortage and infrastructure investment drives construction demand. Site work resists automation.",                           "€32,000",32000,"Post-16/Vocational", +4.1, "Growing",  "Eurostat / FIEC 2024"),
        new("eu-arch",   "Architects",                     "Construction & Trades","construction","#5c4000",  600, 6.0,"Moderate", "AI generative design tools are transforming concept production. Planning and client consultation retain human architects.",           "€52,000",52000,"Bachelor's",         -0.9, "Stable",   "Eurostat / ACE 2024"),
        new("eu-cpm",    "Construction Project Managers",  "Construction & Trades","construction","#5c4000",  900, 5.0,"Moderate", "EU infrastructure projects require experienced human PMs. BIM and AI scheduling assist significantly.",                              "€62,000",62000,"Bachelor's",         +4.7, "Stable",   "Eurostat 2024"),

        // ── Manufacturing & Engineering ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
        new("eu-mo",     "Factory & Machine Operators",    "Manufacturing & Engineering","manufacturing","#3d405b", 8500, 5.0,"Moderate","EU manufacturing has strong automation investment. Remaining operators configure and supervise complex systems.",                "€30,000",30000,"Post-16/Vocational", -7.4, "Declining","Eurostat / BUSINESSEUROPE 2024"),
        new("eu-ae",     "Automotive Engineers & Workers", "Manufacturing & Engineering","manufacturing","#3d405b", 3200, 6.0,"Moderate","EV transition disrupts traditional automotive skills. Battery and software engineering grow; ICE assembly declines.",          "€42,000",42000,"Post-16/Vocational", -5.1, "Stable",   "Eurostat / ACEA 2024"),
        new("eu-qc",     "Quality Control Inspectors",     "Manufacturing & Engineering","manufacturing","#3d405b", 1200, 7.0,"High",     "Computer vision AI is highly capable in manufacturing QC. Human inspectors supervise automated systems.",                      "€32,000",32000,"Post-16/Vocational",-10.3, "Declining","Eurostat 2024"),
        new("eu-me",     "Mechanical Engineers",           "Manufacturing & Engineering","manufacturing","#3d405b", 1800, 6.0,"Moderate", "CAD generation and simulation are AI-assisted. Novel engineering design requires experienced engineers.",                      "€52,000",52000,"Bachelor's",         +2.8, "Stable",   "Eurostat / FEANI 2024"),
        new("eu-pe",     "Process & Chemical Engineers",   "Manufacturing & Engineering","manufacturing","#3d405b",  600, 6.0,"Moderate", "EU chemical and pharma industries require rigorous process control. Safety-critical decisions remain human.",                  "€58,000",58000,"Bachelor's",         +3.2, "Stable",   "Eurostat 2024"),

        // ── Administration & Management ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
        new("eu-sec",    "Secretaries & Admin Assistants", "Administration & Management","admin","#4e5340", 5500, 8.0,"High",    "Standard admin, scheduling and correspondence are highly automatable.",                                                                  "€28,000",28000,"No degree/HS",      -13.7, "Declining","Eurostat 2024"),
        new("eu-rec",    "Receptionists",                  "Administration & Management","admin","#4e5340", 2000, 7.0,"High",    "Automated check-in systems are replacing physical reception across EU offices, hotels and healthcare.",                                 "€24,000",24000,"No degree/HS",       -9.8, "Declining","Eurostat 2024"),
        new("eu-hr",     "HR Managers",                    "Administration & Management","admin","#4e5340", 1800, 6.0,"Moderate","EU employment law complexity (Works Councils, codetermination) keeps HR roles human. Screening is AI-driven.",                          "€52,000",52000,"Bachelor's",         +3.4, "Stable",   "Eurostat / EAPM 2024"),
        new("eu-mktm",   "Marketing Managers",             "Administration & Management","admin","#4e5340", 2200, 7.0,"High",    "Content, campaign management and SEO are AI-automatable. Brand strategy and EU market localisation are resilient.",                     "€55,000",55000,"Bachelor's",         +3.9, "Stable",   "Eurostat 2024"),
        new("eu-projm",  "Project Managers",               "Administration & Management","admin","#4e5340", 2500, 6.0,"Moderate","EU cross-border project management requires human PMs. Tools and reporting are AI-assisted.",                                           "€58,000",58000,"Bachelor's",         +5.8, "Stable",   "Eurostat / IPMA 2024"),
        new("eu-bka",    "Bookkeeping & Payroll Clerks",   "Administration & Management","admin","#4e5340", 3500, 9.0,"Very High","Routine financial processing across EU is highly automatable. AI accounting platforms dominate.",                                       "€28,000",28000,"No degree/HS",      -17.6, "Declining","Eurostat 2024"),
        new("eu-gmd",    "General Managers & Directors",   "Administration & Management","admin","#4e5340", 4000, 5.0,"Moderate","Strategic leadership and accountability require humans. AI augments but cannot replace executive judgement.",                            "€90,000",90000,"Bachelor's",         +1.9, "Stable",   "Eurostat 2024"),

        // ── Hospitality & Food Service ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
        new("eu-chef",   "Chefs & Cooks",                  "Hospitality & Food","hospitality","#7a2d00", 3500, 2.0,"Minimal",  "EU food culture values culinary craft. Tourism drives sustained demand.",                                                                 "€28,000",28000,"Post-16/Vocational", +4.8, "Growing",  "Eurostat / HOTREC 2024"),
        new("eu-wait",   "Waiting & Bar Staff",            "Hospitality & Food","hospitality","#7a2d00", 5500, 4.0,"Low",      "EU tourism (Spain, Italy, France, Greece) sustains massive hospitality employment. Premium experience requires humans.",                 "€22,000",22000,"No degree/HS",       +3.9, "Stable",   "Eurostat / HOTREC 2024"),
        new("eu-hm",     "Hotel & Tourism Managers",       "Hospitality & Food","hospitality","#7a2d00", 1200, 5.0,"Moderate", "Revenue management is AI-driven. Guest experience and destination partnerships require human managers.",                                 "€42,000",42000,"Bachelor's",         +5.7, "Stable",   "Eurostat / HOTREC 2024"),
        new("eu-tour",   "Tour Guides & Travel Agents",    "Hospitality & Food","hospitality","#7a2d00",  400, 6.0,"Moderate", "Standard booking is automated. Specialist guided tours and bespoke travel design retain human guides.",                                  "€28,000",28000,"Post-16/Vocational", -4.3, "Declining","Eurostat / ECTAA 2024"),

        // ── Creative & Media ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
        new("eu-jour",   "Journalists & Reporters",        "Creative & Media","creative","#3a5a40",  500, 7.0,"High",     "Automated news generation is established. Investigative journalism and EU political reporting retain human journalists.",                      "€38,000",38000,"Bachelor's",        -12.4, "Declining","Eurostat / IFJ 2024"),
        new("eu-gfx",    "Graphic & Multimedia Designers", "Creative & Media","creative","#3a5a40", 1200, 8.0,"High",     "AI design generation is transforming commercial creative work. High-concept and brand identity work retain specialist designers.",             "€35,000",35000,"Bachelor's",         -8.1, "Declining","Eurostat / BEDA 2024"),
        new("eu-trans",  "Translators & Interpreters",     "Creative & Media","creative","#3a5a40",  200, 8.0,"High",     "EU institutional translation adopted machine translation early (DeepL, eTranslation). Humans focus on complex legal and literary texts.",    "€42,000",42000,"Bachelor's",        -14.7, "Declining","Eurostat / FIT 2024"),
        new("eu-writ",   "Content Writers & Copywriters",  "Creative & Media","creative","#3a5a40",  600, 9.0,"Very High","AI-generated content is competitive for standard commercial copy. Premium brand writing retains human writers.",                               "€32,000",32000,"Bachelor's",         -9.6, "Declining","Eurostat 2024"),

        // ── Agriculture & Environment ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
        new("eu-farm",   "Farmers & Farm Managers",        "Agriculture & Environment","agriculture","#386641", 4500, 3.0,"Low",  "EU CAP subsidies sustain farming. Precision agriculture AI assists but farm management remains human.",                                "€28,000",28000,"No degree/HS",       -4.8, "Declining","Eurostat / COPA-COGECA 2024"),
        new("eu-faw",    "Agricultural Workers",           "Agriculture & Environment","agriculture","#386641", 8000, 3.0,"Low",  "EU agriculture employs large seasonal workforces. Harvesting robots are emerging but terrain limits scale.",                           "€20,000",20000,"No degree/HS",       -8.3, "Declining","Eurostat / EFFAT 2024"),
        new("eu-vet",    "Veterinary Surgeons",            "Agriculture & Environment","agriculture","#386641",  600, 4.0,"Low",  "Animal health requires physical examination. AI assists diagnostics but cannot replace clinical judgement.",                           "€52,000",52000,"Doctoral/Prof",      +5.9, "Stable",   "Eurostat / FVE 2024"),
        new("eu-env",    "Environmental & Climate Scientists","Agriculture & Environment","agriculture","#386641",400,6.0,"Moderate","EU Green Deal creates demand. Fieldwork and policy engagement are human; data modelling is AI-assisted.",                           "€45,000",45000,"Master's",          +10.3, "Growing",  "Eurostat / EEA 2024"),
        new("eu-energy", "Renewable Energy Technicians",   "Agriculture & Environment","agriculture","#386641",  600, 3.0,"Low",  "EU energy transition creates strong demand. Physical installation and maintenance resist automation.",                                  "€38,000",38000,"Post-16/Vocational",+18.4, "Growing",  "Eurostat / IRENA 2024"),

        // ── Public Services & Defence ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
        new("eu-pol",    "Police Officers",                "Public Services & Defence","publicservices","#1b2a3b", 1500, 4.0,"Low",      "Physical policing and community engagement are human. AI assists with significant EU AI Act restrictions.",                     "€36,000",36000,"No degree/HS",       -1.8, "Stable",   "Eurostat / CEPOL 2024"),
        new("eu-civil",  "Civil Servants (Admin Grades)",  "Public Services & Defence","publicservices","#1b2a3b", 8000, 8.0,"High",     "EU public administration processes and benefit administration are substantially AI-automatable.",                               "€32,000",32000,"Bachelor's",         -4.1, "Declining","Eurostat / EUPAN 2024"),
        new("eu-fire",   "Firefighters & Emergency Services","Public Services & Defence","publicservices","#1b2a3b",400,2.0,"Minimal",   "Emergency response requires physical presence and dynamic decision-making in extreme environments.",                            "€35,000",35000,"Post-16/Vocational",  0.0, "Stable",   "Eurostat / CTIF 2024"),
        new("eu-arm",    "Armed Forces Personnel",         "Public Services & Defence","publicservices","#1b2a3b", 1500, 3.0,"Low",      "EU defence requires human soldiers and officers. AI augments intelligence and logistics.",                                      "€32,000",32000,"No degree/HS",       -1.6, "Stable",   "Eurostat / EDA 2024"),
        new("eu-customs","Customs & Border Officers",      "Public Services & Defence","publicservices","#1b2a3b",  200, 6.0,"Moderate", "AI scanning and risk profiling assist significantly. Physical inspection and legal compliance require human officers.",          "€38,000",38000,"Bachelor's",         +1.2, "Stable",   "Eurostat / WCO 2024"),
    };
}
