using AIJobExposure.Models;

namespace AIJobExposure.Data;

/// <summary>
/// UK occupations. Employment in thousands. Employment change % is 3-year ONS LFS trend (approx 2021–2024).
/// Sources: ONS LFS, sector bodies, ONS Occupational Outlook 2024.
/// </summary>
public static class UkOccupationData
{
    public static List<Occupation> Get() => new()
    {
        // Id, Name, Sector, SectorId, SectorColour, Employment(K), AIScore, Tier, Rationale, Salary, SalaryNum, Education, Change3Yr%, Growth, Source

        // ── Healthcare & Social Care ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
        new("uk-rn",     "Registered Nurses",             "Healthcare & Social Care","healthcare","#1d4e89",  350, 4.0,"Low",      "Clinical assessment and patient care require human empathy and physical presence. AI assists triage and documentation.",                  "£35,400",35400,"Bachelor's",         +5.1, "Growing",   "ONS LFS / NHS Digital 2024"),
        new("uk-gp",     "GPs & Hospital Doctors",        "Healthcare & Social Care","healthcare","#1d4e89",  180, 5.0,"Moderate", "AI aids diagnostics and imaging, but complex clinical judgement and patient relationships require human doctors.",                       "£93,000",93000,"Doctoral/Prof",      +3.2, "Growing",   "ONS LFS / GMC 2024"),
        new("uk-cw",     "Care Workers & Home Carers",    "Healthcare & Social Care","healthcare","#1d4e89", 1800, 2.0,"Minimal",  "Physical, emotional caregiving is extremely difficult to automate. AI monitoring tools support but cannot replace human carers.",       "£22,400",22400,"No degree/HS",       +8.3, "Growing",   "ONS LFS 2024"),
        new("uk-ph",     "Pharmacists",                   "Healthcare & Social Care","healthcare","#1d4e89",   80, 6.0,"Moderate", "Automated dispensing is advancing. Clinical pharmacy and patient counselling require human expertise.",                                 "£47,000",47000,"Master's",           +2.1, "Stable",    "ONS LFS / GPhC 2024"),
        new("uk-dent",   "Dentists",                      "Healthcare & Social Care","healthcare","#1d4e89",   40, 3.0,"Low",      "Manual dexterity and patient examination are central. AI aids X-ray analysis but cannot perform treatment.",                            "£67,000",67000,"Doctoral/Prof",      -1.8, "Stable",    "ONS LFS / GDC 2024"),
        new("uk-physio", "Physiotherapists",              "Healthcare & Social Care","healthcare","#1d4e89",   60, 3.0,"Low",      "Hands-on treatment and individualised rehabilitation planning resist automation.",                                                      "£35,400",35400,"Bachelor's",         +6.2, "Growing",   "ONS LFS 2024"),
        new("uk-rad",    "Medical Radiographers",         "Healthcare & Social Care","healthcare","#1d4e89",   30, 7.0,"High",     "AI matches or exceeds human accuracy in many imaging tasks. Equipment operation still requires humans but analytical roles are exposed.", "£37,300",37300,"Bachelor's",         +4.1, "Stable",    "ONS LFS / HCPC 2024"),
        new("uk-sw",     "Social Workers",                "Healthcare & Social Care","healthcare","#1d4e89",  100, 4.0,"Low",      "Safeguarding and relationship-based practice require human judgement and legal accountability.",                                        "£35,000",35000,"Bachelor's",         +3.4, "Growing",   "ONS LFS 2024"),
        new("uk-paramd", "Paramedics",                    "Healthcare & Social Care","healthcare","#1d4e89",   30, 2.0,"Minimal",  "Emergency physical response in uncontrolled environments is extremely difficult to automate.",                                          "£35,400",35400,"Post-16/Vocational", +5.3, "Growing",   "ONS LFS 2024"),
        new("uk-mhn",    "Mental Health Nurses",          "Healthcare & Social Care","healthcare","#1d4e89",   50, 4.0,"Low",      "Therapeutic relationships and risk assessment require deep human empathy.",                                                             "£35,400",35400,"Bachelor's",         +8.7, "Growing",   "ONS LFS 2024"),

        // ── Education & Training ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
        new("uk-pt",     "Primary School Teachers",       "Education & Training","education","#2d6a4f",  200, 3.0,"Low",      "Child development and pastoral care require constant human adaptation.",                                                                   "£30,000",30000,"Bachelor's",         -0.9, "Stable",    "ONS LFS / DfE 2024"),
        new("uk-st",     "Secondary School Teachers",     "Education & Training","education","#2d6a4f",  220, 4.0,"Low",      "Subject expertise and student mentorship require human presence, though AI automates marking and planning.",                               "£35,000",35000,"Bachelor's",         +1.2, "Stable",    "ONS LFS / DfE 2024"),
        new("uk-ul",     "University Lecturers",          "Education & Training","education","#2d6a4f",  200, 5.0,"Moderate", "Lecture delivery and basic feedback are highly AI-automatable. Research and supervision are less so.",                                     "£48,000",48000,"Doctoral/Prof",      +1.8, "Stable",    "ONS LFS / HESA 2024"),
        new("uk-ta",     "Teaching Assistants",           "Education & Training","education","#2d6a4f",  350, 5.0,"Moderate", "Physical classroom support is hard to automate; administrative and basic instructional tasks face AI substitution.",                       "£20,500",20500,"Post-16/Vocational", -2.1, "Stable",    "ONS LFS / DfE 2024"),
        new("uk-ey",     "Early Years Workers",           "Education & Training","education","#2d6a4f",  200, 2.0,"Minimal",  "Physical care and play-based development require constant human presence.",                                                                "£19,500",19500,"No degree/HS",       -3.4, "Growing",   "ONS LFS 2024"),
        new("uk-tn",     "Corporate Trainers",            "Education & Training","education","#2d6a4f",   80, 7.0,"High",     "Course content and e-learning modules are rapidly automated by AI tools.",                                                                 "£42,000",42000,"Bachelor's",         -8.2, "Declining", "ONS LFS 2024"),

        // ── Technology & IT ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
        new("uk-sd",     "Software Developers",           "Technology & IT","technology","#6b2d8b",  500, 8.0,"High",     "AI code generation is highly capable. Value shifts to architecture and oversight of AI-generated code.",                                       "£65,000",65000,"Bachelor's",        +12.4, "Growing",   "ONS LFS / Tech Nation 2024"),
        new("uk-da",     "Data Analysts & Scientists",    "Technology & IT","technology","#6b2d8b",  150, 9.0,"Very High","Routine querying, dashboards and reports are now almost entirely AI-automatable.",                                                             "£55,000",55000,"Bachelor's",        +22.1, "Growing",   "ONS LFS / Tech Nation 2024"),
        new("uk-itm",    "IT Managers",                   "Technology & IT","technology","#6b2d8b",  200, 6.0,"Moderate", "Vendor management and strategic planning resist automation; technical tasks increasingly delegated to AI.",                                    "£70,000",70000,"Bachelor's",         +5.3, "Stable",    "ONS LFS 2024"),
        new("uk-cs",     "Cybersecurity Specialists",     "Technology & IT","technology","#6b2d8b",  100, 7.0,"High",     "Threat detection is heavily AI-assisted. Adversarial creativity and strategic risk management require humans.",                                "£68,000",68000,"Bachelor's",        +18.3, "Growing",   "ONS LFS / DCMS 2024"),
        new("uk-ne",     "Network Engineers",             "Technology & IT","technology","#6b2d8b",   80, 6.0,"Moderate", "Physical infrastructure resists automation; monitoring and configuration are increasingly AI-assisted.",                                       "£52,000",52000,"Post-16/Vocational", -2.1, "Stable",    "ONS LFS 2024"),
        new("uk-ux",     "UX & UI Designers",             "Technology & IT","technology","#6b2d8b",   60, 7.0,"High",     "Design generation and prototyping are heavily AI-augmented. Strategic UX research remains human-led.",                                        "£55,000",55000,"Bachelor's",         +8.4, "Growing",   "ONS LFS 2024"),
        new("uk-its",    "IT Support Technicians",        "Technology & IT","technology","#6b2d8b",  150, 6.0,"Moderate", "Tier-1 and Tier-2 helpdesk increasingly automated. Complex hardware support persists.",                                                       "£28,000",28000,"Post-16/Vocational", -5.2, "Declining", "ONS LFS 2024"),

        // ── Finance & Insurance ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
        new("uk-ac",     "Accountants & Auditors",        "Finance & Insurance","finance","#7b3f00",  350, 8.0,"High",     "Bookkeeping and standard tax preparation are highly automatable. Complex advisory and audit judgement retain value.",                          "£52,000",52000,"Bachelor's",         -4.3, "Stable",    "ONS LFS / ICAEW 2024"),
        new("uk-fa",     "Financial Analysts",            "Finance & Insurance","finance","#7b3f00",  150, 8.0,"High",     "Data aggregation and standard modelling are largely automatable. Investment thesis and relationships remain human.",                           "£65,000",65000,"Bachelor's",         +2.1, "Stable",    "ONS LFS 2024"),
        new("uk-iu",     "Insurance Underwriters",        "Finance & Insurance","finance","#7b3f00",   50, 8.0,"High",     "Risk scoring and standard policy pricing are AI-driven. Novel risk assessment retains human involvement.",                                    "£48,000",48000,"Bachelor's",         -8.1, "Declining", "ONS LFS / ABI 2024"),
        new("uk-bc",     "Bank Clerks & Cashiers",        "Finance & Insurance","finance","#7b3f00",  100, 9.0,"Very High","Routine transactions are almost entirely automated. Role limited to exception handling.",                                                     "£24,000",24000,"No degree/HS",      -18.4, "Declining", "ONS LFS / UK Finance 2024"),
        new("uk-fad",    "Financial Advisers",            "Finance & Insurance","finance","#7b3f00",  150, 6.0,"Moderate", "Regulatory requirements keep human advisers central to complex planning. AI assists portfolio construction.",                                  "£55,000",55000,"Bachelor's",         +1.3, "Stable",    "ONS LFS / FCA 2024"),
        new("uk-act",    "Actuaries",                     "Finance & Insurance","finance","#7b3f00",   20, 8.0,"High",     "Core calculations are AI-automatable. Regulatory sign-off and novel risk modelling require qualified actuaries.",                             "£85,000",85000,"Master's",           +3.1, "Stable",    "ONS LFS / IFoA 2024"),

        // ── Legal & Professional ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
        new("uk-sol",    "Solicitors",                    "Legal & Professional","legal","#4a1942",  150, 7.0,"High",     "Legal research and standard drafting are AI-automatable. Advocacy, client strategy and novel judgements are resilient.",                       "£62,000",62000,"Doctoral/Prof",      +3.2, "Stable",    "ONS LFS / SRA 2024"),
        new("uk-bar",    "Barristers",                    "Legal & Professional","legal","#4a1942",   20, 6.0,"Moderate", "Oral advocacy and strategic legal argument are difficult to automate. Research is exposed.",                                                   "£95,000",95000,"Doctoral/Prof",      +1.1, "Stable",    "ONS LFS / Bar Council 2024"),
        new("uk-pleg",   "Paralegals",                    "Legal & Professional","legal","#4a1942",  100, 8.0,"High",     "Document review, due diligence and contract comparison are the most AI-exposed legal tasks.",                                                  "£28,000",28000,"Bachelor's",         -6.4, "Declining", "ONS LFS 2024"),
        new("uk-mc",     "Management Consultants",        "Legal & Professional","legal","#4a1942",  100, 7.0,"High",     "Data analysis and benchmarking are AI-automatable. Strategic facilitation and client trust are resilient.",                                    "£75,000",75000,"Master's",           +4.1, "Stable",    "ONS LFS / MCA 2024"),

        // ── Retail & Customer Service ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
        new("uk-rsa",    "Retail Sales Assistants",       "Retail & Customer Service","retail","#a05c00", 2800, 6.0,"Moderate","Physical stocking and complex service resist automation; checkout and basic enquiries are heavily automated.",                             "£21,000",21000,"No degree/HS",       -7.2, "Declining", "ONS LFS / BRC 2024"),
        new("uk-cash",   "Cashiers",                      "Retail & Customer Service","retail","#a05c00",  200, 9.0,"Very High","Self-checkout and contactless payment are rapidly displacing cashier roles across retail and hospitality.",                               "£20,500",20500,"No degree/HS",      -22.1, "Declining", "ONS LFS 2024"),
        new("uk-csa",    "Customer Service Agents",       "Retail & Customer Service","retail","#a05c00",  800, 8.0,"High",    "First-line queries are handled by AI chatbots. Complex and escalated cases retain human agents.",                                         "£23,000",23000,"No degree/HS",       -9.3, "Declining", "ONS LFS 2024"),
        new("uk-smgr",   "Sales Managers",                "Retail & Customer Service","retail","#a05c00",  200, 6.0,"Moderate","CRM analysis and pipeline reporting are AI-driven. Complex negotiation and team leadership are human.",                                   "£52,000",52000,"Bachelor's",         +2.1, "Stable",    "ONS LFS 2024"),
        new("uk-buy",    "Buyers & Procurement Officers", "Retail & Customer Service","retail","#a05c00",  100, 7.0,"High",    "Demand forecasting and supplier comparison are AI-generated. Strategic sourcing relationships resist automation.",                        "£42,000",42000,"Bachelor's",         +3.4, "Stable",    "ONS LFS 2024"),

        // ── Transport & Logistics ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
        new("uk-hgv",    "HGV / Lorry Drivers",           "Transport & Logistics","transport","#0a4b6e",  300, 4.0,"Low",      "Autonomous long-haul driving remains years from UK commercial scale.",                                                                     "£36,000",36000,"Post-16/Vocational", -3.1, "Stable",    "ONS LFS / DVSA 2024"),
        new("uk-del",    "Delivery Drivers",              "Transport & Logistics","transport","#0a4b6e",  400, 4.0,"Low",      "Drone delivery pilots exist but full residential deployment is far off. AI optimises routing significantly.",                               "£26,000",26000,"No degree/HS",      +14.2, "Stable",    "ONS LFS 2024"),
        new("uk-bus",    "Bus & Coach Drivers",           "Transport & Logistics","transport","#0a4b6e",  100, 3.0,"Low",      "Autonomous public transport requires extensive infrastructure and regulatory approval.",                                                   "£28,500",28500,"Post-16/Vocational", -4.1, "Stable",    "ONS LFS 2024"),
        new("uk-war",    "Warehouse Operatives",          "Transport & Logistics","transport","#0a4b6e",  800, 5.0,"Moderate", "Robotic picking is advancing in fulfilment centres but requires high capital investment.",                                                 "£24,000",24000,"No degree/HS",       +3.2, "Declining", "ONS LFS 2024"),
        new("uk-lm",     "Logistics & Supply Chain Mgrs", "Transport & Logistics","transport","#0a4b6e",  150, 6.0,"Moderate", "Network planning is AI-assisted. Supplier relationships and crisis management require human judgement.",                                  "£55,000",55000,"Bachelor's",         +6.1, "Stable",    "ONS LFS 2024"),
        new("uk-pilot",  "Airline Pilots",                "Transport & Logistics","transport","#0a4b6e",   20, 3.0,"Low",      "UK regulations mandate two pilots. Full autonomous commercial flight is many decades away.",                                               "£98,000",98000,"Post-16/Vocational", +8.3, "Stable",    "CAA / ONS 2024"),

        // ── Construction & Trades ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
        new("uk-elec",   "Electricians",                  "Construction & Trades","construction","#5c4000",  200, 2.0,"Minimal",  "Installation and compliance testing require manual dexterity in unstructured environments.",                                            "£38,000",38000,"Post-16/Vocational", +9.1, "Growing",   "ONS LFS / ECA 2024"),
        new("uk-plumb",  "Plumbers & Heating Engineers",  "Construction & Trades","construction","#5c4000",  150, 2.0,"Minimal",  "Fault diagnosis in domestic plumbing is highly contextual and physical.",                                                              "£38,500",38500,"Post-16/Vocational", +7.3, "Growing",   "ONS LFS 2024"),
        new("uk-brick",  "Bricklayers & Masons",          "Construction & Trades","construction","#5c4000",  100, 1.0,"Minimal",  "On-site variability and complex geometries keep bricklaying highly manual.",                                                           "£34,000",34000,"Post-16/Vocational", +3.1, "Growing",   "ONS LFS / CITB 2024"),
        new("uk-carp",   "Carpenters & Joiners",          "Construction & Trades","construction","#5c4000",  150, 2.0,"Minimal",  "Custom fitting and joinery craftsmanship are highly resistant to automation.",                                                        "£34,000",34000,"Post-16/Vocational", +2.4, "Growing",   "ONS LFS 2024"),
        new("uk-arch",   "Architects",                    "Construction & Trades","construction","#5c4000",   30, 6.0,"Moderate", "AI generates floor plans rapidly. Design vision, planning consent and client liaison are human-led.",                                  "£50,000",50000,"Bachelor's",         -1.2, "Stable",    "ONS LFS / ARB 2024"),
        new("uk-cpm",    "Construction Project Managers", "Construction & Trades","construction","#5c4000",  100, 5.0,"Moderate", "Multi-stakeholder coordination requires human judgement. Scheduling and cost reporting are AI-assisted.",                              "£60,000",60000,"Bachelor's",         +4.2, "Stable",    "ONS LFS / CIOB 2024"),

        // ── Manufacturing & Engineering ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
        new("uk-mo",     "Machine Operators",             "Manufacturing & Engineering","manufacturing","#3d405b",  400, 5.0,"Moderate","CNC and automated machinery displaced many operators. Remaining workers configure and maintain complex systems.",                  "£28,000",28000,"Post-16/Vocational", -6.3, "Declining", "ONS LFS 2024"),
        new("uk-qc",     "Quality Control Inspectors",   "Manufacturing & Engineering","manufacturing","#3d405b",  100, 7.0,"High",     "Computer vision AI is highly capable in QC. Human inspectors supervise automated systems.",                                      "£30,000",30000,"Post-16/Vocational", -9.2, "Declining", "ONS LFS 2024"),
        new("uk-me",     "Mechanical Engineers",         "Manufacturing & Engineering","manufacturing","#3d405b",  100, 6.0,"Moderate", "FEA simulation and CAD generation are AI-augmented. Novel design and on-site problem solving retain value.",                    "£45,000",45000,"Bachelor's",         +3.1, "Stable",    "ONS LFS / IMechE 2024"),
        new("uk-ee",     "Electrical Engineers",         "Manufacturing & Engineering","manufacturing","#3d405b",   80, 6.0,"Moderate", "Schematic generation and compliance checking are AI-assisted. Novel design requires experienced engineers.",                     "£47,000",47000,"Bachelor's",         +5.2, "Stable",    "ONS LFS / IET 2024"),
        new("uk-weld",   "Welders & Metal Workers",      "Manufacturing & Engineering","manufacturing","#3d405b",   50, 3.0,"Low",      "Automated welding lines exist but bespoke structural welding remains manual.",                                                   "£32,000",32000,"Post-16/Vocational", -4.1, "Stable",    "ONS LFS 2024"),

        // ── Administration & Management ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
        new("uk-sec",    "Secretaries & PAs",             "Administration & Management","admin","#4e5340",  400, 8.0,"High",    "Diary management, travel booking and standard correspondence are heavily AI-automatable.",                                                 "£28,000",28000,"No degree/HS",      -14.2, "Declining", "ONS LFS 2024"),
        new("uk-rec",    "Receptionists",                 "Administration & Management","admin","#4e5340",  300, 7.0,"High",    "Virtual receptionists and AI visitor management are replacing physical reception.",                                                       "£22,500",22500,"No degree/HS",      -10.3, "Declining", "ONS LFS 2024"),
        new("uk-hr",     "HR Managers",                   "Administration & Management","admin","#4e5340",  200, 6.0,"Moderate","Recruitment screening and onboarding are AI-assisted. Employee relations require human judgement.",                                       "£50,000",50000,"Bachelor's",         +3.1, "Stable",    "ONS LFS / CIPD 2024"),
        new("uk-mktm",   "Marketing Managers",            "Administration & Management","admin","#4e5340",  250, 7.0,"High",    "Content creation and campaign optimisation are substantially AI-driven. Brand strategy retains human value.",                             "£52,000",52000,"Bachelor's",         +4.3, "Stable",    "ONS LFS / CIM 2024"),
        new("uk-projm",  "Project Managers",              "Administration & Management","admin","#4e5340",  300, 6.0,"Moderate","Scheduling and reporting are AI-assisted. Stakeholder communication and risk judgement remain human.",                                    "£55,000",55000,"Bachelor's",         +6.2, "Stable",    "ONS LFS / APM 2024"),
        new("uk-gmd",    "General Managers & Directors",  "Administration & Management","admin","#4e5340",  800, 5.0,"Moderate","Strategic leadership and accountability require humans. AI augments but cannot replace executive judgement.",                             "£80,000",80000,"Bachelor's",         +2.1, "Stable",    "ONS LFS 2024"),
        new("uk-bka",    "Bookkeeping & Payroll Clerks",  "Administration & Management","admin","#4e5340",  200, 9.0,"Very High","Routine transaction processing and reconciliation are almost entirely automated by modern accounting platforms.",                        "£24,000",24000,"No degree/HS",      -16.3, "Declining", "ONS LFS 2024"),

        // ── Hospitality & Food Service ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
        new("uk-chef",   "Chefs & Cooks",                 "Hospitality & Food","hospitality","#7a2d00",  200, 2.0,"Minimal",  "Culinary creativity and live kitchen management require skilled human chefs.",                                                              "£27,000",27000,"Post-16/Vocational", +5.1, "Growing",   "ONS LFS / UKHospitality 2024"),
        new("uk-wait",   "Waiting Staff",                 "Hospitality & Food","hospitality","#7a2d00",  400, 4.0,"Low",      "Hospitality experience and upselling require human interaction in most establishments.",                                                   "£21,000",21000,"No degree/HS",       +4.2, "Stable",    "ONS LFS 2024"),
        new("uk-bars",   "Bar Staff",                     "Hospitality & Food","hospitality","#7a2d00",  200, 3.0,"Low",      "Social interaction and premium experience keep bar work predominantly human.",                                                             "£20,500",20500,"No degree/HS",       +2.1, "Stable",    "ONS LFS 2024"),
        new("uk-hm",     "Hotel & Accommodation Managers","Hospitality & Food","hospitality","#7a2d00",  100, 5.0,"Moderate", "Revenue management is AI-driven. Guest experience and team leadership are human.",                                                        "£38,000",38000,"Bachelor's",         +6.3, "Stable",    "ONS LFS 2024"),
        new("uk-ka",     "Kitchen Assistants & Fast Food","Hospitality & Food","hospitality","#7a2d00",  700, 4.0,"Low",      "Kiosk ordering grows but full food assembly robot deployment at scale remains limited.",                                                   "£20,000",20000,"No degree/HS",       +1.4, "Stable",    "ONS LFS 2024"),

        // ── Creative & Media ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
        new("uk-jour",   "Journalists & Reporters",       "Creative & Media","creative","#3a5a40",   50, 7.0,"High",     "Automated reporting for structured data is established. Investigative journalism and editorial judgement are resilient.",                        "£36,000",36000,"Bachelor's",        -11.2, "Declining", "ONS LFS / NUJ 2024"),
        new("uk-gfx",    "Graphic Designers",             "Creative & Media","creative","#3a5a40",  100, 8.0,"High",     "AI image generation is highly capable for commercial work. Brand strategy and conceptual direction retain value.",                              "£32,000",32000,"Bachelor's",         -7.4, "Declining", "ONS LFS / D&AD 2024"),
        new("uk-mkpr",   "Marketing & PR Executives",     "Creative & Media","creative","#3a5a40",  250, 7.0,"High",     "Copy and social scheduling are AI-automatable. Campaign strategy and press relationships require humans.",                                      "£38,000",38000,"Bachelor's",         +3.1, "Stable",    "ONS LFS 2024"),
        new("uk-writ",   "Writers & Authors",             "Creative & Media","creative","#3a5a40",   50, 8.0,"High",     "Long-form content and copywriting are heavily AI-augmented. Literary fiction commands premium.",                                               "£28,000",28000,"Bachelor's",         -5.3, "Declining", "ONS LFS 2024"),

        // ── Agriculture & Environment ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
        new("uk-farm",   "Farmers & Farm Managers",       "Agriculture & Environment","agriculture","#386641",  150, 3.0,"Low",  "Precision agriculture AI assists but strategic farm management remains human.",                                                         "£30,000",30000,"No degree/HS",       -4.2, "Stable",    "ONS LFS / DEFRA 2024"),
        new("uk-faw",    "Agricultural Workers",          "Agriculture & Environment","agriculture","#386641",  200, 3.0,"Low",  "UK soft-fruit picking remains manual due to terrain variability.",                                                                      "£22,000",22000,"No degree/HS",       -6.1, "Declining", "ONS LFS / DEFRA 2024"),
        new("uk-vet",    "Veterinary Surgeons",           "Agriculture & Environment","agriculture","#386641",   30, 4.0,"Low",  "Animal examination and surgery require physical presence. AI assists imaging and drug dosing.",                                          "£48,000",48000,"Doctoral/Prof",      +6.3, "Growing",   "ONS LFS / RCVS 2024"),
        new("uk-env",    "Environmental Scientists",      "Agriculture & Environment","agriculture","#386641",   30, 6.0,"Moderate","Field sampling requires physical presence. Data modelling is increasingly AI-assisted.",                                              "£38,000",38000,"Master's",           +9.1, "Growing",   "ONS LFS 2024"),

        // ── Public Services & Defence ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
        new("uk-pol",    "Police Officers",               "Public Services & Defence","publicservices","#1b2a3b",  150, 4.0,"Low",      "Physical policing and community relations resist automation. AI assists analysis and evidence processing.",                       "£32,000",32000,"No degree/HS",       -2.1, "Stable",    "ONS LFS / NPCC 2024"),
        new("uk-fire",   "Firefighters",                  "Public Services & Defence","publicservices","#1b2a3b",   30, 2.0,"Minimal",  "Dynamic emergency response is extremely hard to automate.",                                                                      "£33,500",33500,"Post-16/Vocational",  0.0, "Stable",    "ONS LFS / NFCC 2024"),
        new("uk-civil",  "Civil Servants (Admin Grades)", "Public Services & Defence","publicservices","#1b2a3b",  400, 8.0,"High",     "Administrative processing and standard case handling in government are substantially AI-automatable.",                            "£30,000",30000,"Bachelor's",         -3.2, "Declining", "ONS LFS / Cabinet Office 2024"),
        new("uk-arm",    "Armed Forces Personnel",        "Public Services & Defence","publicservices","#1b2a3b",  150, 3.0,"Low",      "Physical military roles require human presence. AI assists logistics and intelligence.",                                          "£30,000",30000,"No degree/HS",       -1.4, "Stable",    "MOD / ONS 2024"),
    };
}
